### ISSUE TITLE
Week4  problem 5 and 6 missing

### ISSUE THREAD

**Issue by tasawar-hussain** [AbdallahHemdan/Algorithmic-Toolbox-San-Diego#4]
The implementation for the two problems from week is missing :
[organizing a lottery](https://github.com/AbdallahHemdan/Algorithmic-Toolbox-San-Diego/blob/master/week4_programming_challenges/5_organizing_a_lottery)
[Closest Points](https://github.com/AbdallahHemdan/Algorithmic-Toolbox-San-Diego/blob/master/week4_programming_challenges/6_closest_points)

Please update the readme accordingly!

**Comment by AbdallahHemdan** [comment]
Thanks Tasawar. I will upload them right now.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
05/29/20,
03:25:35 PM

**Comment by AbdallahHemdan** [comment]
Thanks, Tasawar I have just added the solution of the 2 problems and Sync them with the readme file. 
- [organizing a lottery](https://github.com/AbdallahHemdan/Algorithmic-Toolbox-San-Diego/blob/master/week4_programming_challenges/5_organizing%20a%20lottery/organizing%20a%20lottery.cpp) 
- [Closest Points](https://github.com/AbdallahHemdan/Algorithmic-Toolbox-San-Diego/blob/master/week4_programming_challenges/6_Closest_Points/Closest_Points.cpp)
